/**
CODE VIDE QUI CREE UN CANEVAS DE 512x512 PIXELS.
*/

/**
 DEBUT DE LA FONCTION setup()
 QUI DETERMINE LE CODE A EXECUTER
 AU DEMARRAGE
 */
function setup() {
  // CREER LE CANVAS
  createCanvas(512, 512);

  // CODE PERSONNALISE A EXECUTER AU DEMARRAGE :


} // FIN DE LA FONCTION setup()
